-- MySQL Script generated by MySQL Workbench
-- Thu Feb 26 18:23:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movie_rental_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_rental_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_rental_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `movie_rental_db` ;

-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `Balance` DECIMAL(19,2) NOT NULL,
  `PasswordHash` BINARY(64) NOT NULL,
  `Email` VARCHAR(320) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts_card_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts_card_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts_card_payment_methods` (
  `AccountID` INT UNSIGNED NOT NULL,
  `CardID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AccountID`, `CardID`),
  CONSTRAINT `FK_accounts_card_payment_methods_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_accounts_card_payment_methods_card`
    FOREIGN KEY (`CardID`)
    REFERENCES `movie_rental_db`.`card_payment_methods` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_accounts_card_payment_methods_card_idx` ON `movie_rental_db`.`accounts_card_payment_methods` (`CardID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts_paypal_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts_paypal_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts_paypal_payment_methods` (
  `AccountID` INT UNSIGNED NOT NULL,
  `PaypalID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AccountID`, `PaypalID`),
  CONSTRAINT `FK_accounts_paypal_payment_methods_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_accounts_paypal_payment_methods_paypal`
    FOREIGN KEY (`PaypalID`)
    REFERENCES `movie_rental_db`.`paypal_payment_methods` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_accounts_paypal_payment_methods_paypal_idx` ON `movie_rental_db`.`accounts_paypal_payment_methods` (`PaypalID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`audit_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`audit_log` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`audit_log` (
  `Operation` CHAR(6) NOT NULL,
  `User` VARCHAR(64) NOT NULL,
  `Table` VARCHAR(64) NOT NULL,
  `PrimaryKeyModified` INT UNSIGNED NULL DEFAULT NULL,
  `TimeStamp` BIGINT UNSIGNED NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`card_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`card_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`card_payment_methods` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CardNumber` VARCHAR(19) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_bookmarks` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_bookmarks` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `BookmarkTime` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`CustomerID`, `MovieID`),
  CONSTRAINT `FK_customer_bookmarks_customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_customer_bookmarks_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_bookmarks_movies_idx` ON `movie_rental_db`.`customer_bookmarks` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_rentings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_rentings` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_rentings` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `PeriodStart` BIGINT UNSIGNED NOT NULL,
  `PeriodEnd` BIGINT UNSIGNED NOT NULL,
  `Price` DECIMAL(19,2) NOT NULL,
  `ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_customer_rentings_customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_customer_rentings_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_rentings_customers` ON `movie_rental_db`.`customer_rentings` (`CustomerID` ASC) VISIBLE;

CREATE INDEX `FK_customer_rentings_movies_idx` ON `movie_rental_db`.`customer_rentings` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_watchtracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_watchtracking` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_watchtracking` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `TimeStamp` BIGINT UNSIGNED NOT NULL,
  `SecondsInMovie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CustomerID`, `MovieID`),
  CONSTRAINT `FK_customer_watchtracking_customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_customer_watchtracking_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_bookmarks_movies_idx` ON `movie_rental_db`.`customer_watchtracking` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`genres` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`genres` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`giftcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`giftcards` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`giftcards` (
  `ID` INT UNSIGNED NOT NULL,
  `CodeHash` BINARY(64) NOT NULL,
  `Amount` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`languages` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CountryCode` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_actors` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_actors` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PersonID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PersonID`),
  CONSTRAINT `FK_Movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_People`
    FOREIGN KEY (`PersonID`)
    REFERENCES `movie_rental_db`.`people` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_People_idx` ON `movie_rental_db`.`movie_actors` (`PersonID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_directors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_directors` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_directors` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PersonID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PersonID`),
  CONSTRAINT `FK_Movies0`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_People0`
    FOREIGN KEY (`PersonID`)
    REFERENCES `movie_rental_db`.`people` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_People_idx` ON `movie_rental_db`.`movie_directors` (`PersonID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_genres` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_genres` (
  `MovieID` INT UNSIGNED NOT NULL,
  `GenreID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `GenreID`),
  CONSTRAINT `FK_genres_movies`
    FOREIGN KEY (`GenreID`)
    REFERENCES `movie_rental_db`.`genres` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_movies_genres`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Genres_idx` ON `movie_rental_db`.`movie_genres` (`GenreID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_publishers` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_publishers` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PublisherID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PublisherID`),
  CONSTRAINT `FK_movies_publishers`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_publishers_movies`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `movie_rental_db`.`publishers` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Genres_idx` ON `movie_rental_db`.`movie_publishers` (`PublisherID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_spoken_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_spoken_languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_spoken_languages` (
  `MovieID` INT UNSIGNED NOT NULL,
  `LanguageID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `LanguageID`),
  CONSTRAINT `FK_Language0`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `movie_rental_db`.`languages` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Movie0`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Language_idx` ON `movie_rental_db`.`movie_spoken_languages` (`LanguageID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_subtitle_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_subtitle_languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_subtitle_languages` (
  `MovieID` INT UNSIGNED NOT NULL,
  `LanguageID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `LanguageID`),
  CONSTRAINT `FK_Language`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `movie_rental_db`.`languages` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Language_idx` ON `movie_rental_db`.`movie_subtitle_languages` (`LanguageID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movies` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movies` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `RuntimeSeconds` INT NOT NULL,
  `MinimumAge` TINYINT NOT NULL,
  `Price` DECIMAL(2,0) NOT NULL,
  `ReleaseDate` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`orderlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`orderlines` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`orderlines` (
  `AccountID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NULL DEFAULT NULL,
  `ID` INT UNSIGNED NOT NULL,
  `GiftcardID` INT UNSIGNED NULL DEFAULT NULL,
  `OrderID` INT UNSIGNED NOT NULL,
  `Price` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_orderlines_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_orderlines_giftcards`
    FOREIGN KEY (`GiftcardID`)
    REFERENCES `movie_rental_db`.`giftcards` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_orderlines_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_orderlines_order`
    FOREIGN KEY (`OrderID`)
    REFERENCES `movie_rental_db`.`orders` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_orderlines_accounts_idx` ON `movie_rental_db`.`orderlines` (`AccountID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_giftcards_idx` ON `movie_rental_db`.`orderlines` (`GiftcardID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_order_idx` ON `movie_rental_db`.`orderlines` (`OrderID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_movies_idx` ON `movie_rental_db`.`orderlines` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`orders` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`orders` (
  `ID` INT UNSIGNED NOT NULL,
  `OrderTimeStamp` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`paypal_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`paypal_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`paypal_payment_methods` (
  `Username` VARCHAR(100) NOT NULL,
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(120) NOT NULL,
  `Password` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`people` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`people` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(200) NOT NULL,
  `LastName` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`publishers` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`publishers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`support_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`support_tickets` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`support_tickets` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `Description` VARCHAR(800) NOT NULL,
  `CreationDate` BIGINT UNSIGNED NOT NULL,
  `CreatedBy` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_support_ticks_created_by`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_support_ticks_created_by_idx` ON `movie_rental_db`.`support_tickets` (`CreatedBy` ASC) VISIBLE;

USE `movie_rental_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `movie_rental_db`.`all_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_rental_db`.`all_accounts` (`ID` INT, `Name` INT, `PhoneNumber` INT, `Balance` INT);

-- -----------------------------------------------------
-- Placeholder table for view `movie_rental_db`.`all_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_rental_db`.`all_movies` (`ID` INT, `Title` INT, `RuntimeSeconds` INT, `MinimumAge` INT, `Price` INT, `ReleaseDate` INT);

-- -----------------------------------------------------
-- procedure CreateLogEntry
-- -----------------------------------------------------

USE `movie_rental_db`;
DROP procedure IF EXISTS `movie_rental_db`.`CreateLogEntry`;

DELIMITER $$
USE `movie_rental_db`$$
CREATE DEFINER=`root`@`%` PROCEDURE `CreateLogEntry`(IN tableName VARCHAR(64), IN operation CHAR(6), IN keyModified INT UNSIGNED)
BEGIN
	INSERT INTO audit_log VALUES
    (operation, SESSION_USER(), tableName, keyModified, UNIX_TIMESTAMP());
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `movie_rental_db`.`all_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`all_accounts`;
DROP VIEW IF EXISTS `movie_rental_db`.`all_accounts` ;
USE `movie_rental_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `movie_rental_db`.`all_accounts` AS select `movie_rental_db`.`accounts`.`ID` AS `ID`,`movie_rental_db`.`accounts`.`Name` AS `Name`,`movie_rental_db`.`accounts`.`PhoneNumber` AS `PhoneNumber`,`movie_rental_db`.`accounts`.`Balance` AS `Balance` from `movie_rental_db`.`accounts`;

-- -----------------------------------------------------
-- View `movie_rental_db`.`all_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`all_movies`;
DROP VIEW IF EXISTS `movie_rental_db`.`all_movies` ;
USE `movie_rental_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `movie_rental_db`.`all_movies` AS select `movie_rental_db`.`movies`.`ID` AS `ID`,`movie_rental_db`.`movies`.`Title` AS `Title`,`movie_rental_db`.`movies`.`RuntimeSeconds` AS `RuntimeSeconds`,`movie_rental_db`.`movies`.`MinimumAge` AS `MinimumAge`,`movie_rental_db`.`movies`.`Price` AS `Price`,`movie_rental_db`.`movies`.`ReleaseDate` AS `ReleaseDate` from `movie_rental_db`.`movies`;
USE `movie_rental_db`;

DELIMITER $$

USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`accounts`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`accounts`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`accounts`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_card_payment_methods_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_card_payment_methods_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`accounts_card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_card_payment_methods', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_card_payment_methods_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_card_payment_methods_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`accounts_card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_card_payment_methods', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_card_payment_methods_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_card_payment_methods_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`accounts_card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_card_payment_methods', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`accounts_paypal_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_card_payment_methods', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`accounts_paypal_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_paypal_payment_methods', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`accounts_paypal_payment_methods_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`accounts_paypal_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('accounts_card_payment_methods', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`audit_log_BEFORE_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`audit_log_BEFORE_INSERT`
BEFORE INSERT ON `movie_rental_db`.`audit_log`
FOR EACH ROW
BEGIN
	IF NEW.TimeStamp IS NULL THEN
		SET NEW.TimeStamp = UNIX_TIMESTAMP();
    END IF;
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`card_payment_methods_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`card_payment_methods_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('card_payment_methods', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`card_payment_methods_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`card_payment_methods_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('card_payment_methods', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`card_payment_methods_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`card_payment_methods_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`card_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('card_payment_methods', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_bookmarks_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_bookmarks_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`customer_bookmarks`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_bookmarks', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_bookmarks_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_bookmarks_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`customer_bookmarks`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_bookmarks', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_bookmarks_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_bookmarks_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`customer_bookmarks`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_bookmarks', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_rentings_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_rentings_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`customer_rentings`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_rentings', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_rentings_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_rentings_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`customer_rentings`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_rentings', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_rentings_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_rentings_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`customer_rentings`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_rentings', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_watchtracking_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_watchtracking_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`customer_watchtracking`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_watchtracking', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_watchtracking_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_watchtracking_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`customer_watchtracking`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_watchtracking', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`customer_watchtracking_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`customer_watchtracking_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`customer_watchtracking`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('customer_watchtracking', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`genres_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`genres_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('genres', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`genres_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`genres_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('genres', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`genres_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`genres_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('genres', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`giftcards_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`giftcards_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`giftcards`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('genres', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`giftcards_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`giftcards_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`giftcards`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('giftcards', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`giftcards_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`giftcards_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`giftcards`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('genres', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`languages_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`languages_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('languages', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`languages_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`languages_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('languages', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`languages_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`languages_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('languages', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_actors_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_actors_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_actors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_actors', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_actors_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_actors_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_actors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_actors', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_actors_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_actors_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_actors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_actors', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_directors_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_directors_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_directors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_directors', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_directors_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_directors_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_directors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_directors', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_directors_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_directors_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_directors`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_directors', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_genres_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_genres_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_genres', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_genres_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_genres_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_genres', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_genres_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_genres_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_genres`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_genres', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_publishers_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_publishers_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_publishers', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_publishers_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_publishers_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_publishers', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_publishers_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_publishers_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_publishers', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_spoken_languages_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_spoken_languages_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_spoken_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_spoken_languages', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_spoken_languages_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_spoken_languages_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_spoken_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_spoken_languages', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_spoken_languages_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_spoken_languages_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_spoken_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_spoken_languages', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_subtitle_languages_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_subtitle_languages_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movie_subtitle_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_subtitle_languages', 'DELETE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_subtitle_languages_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_subtitle_languages_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movie_subtitle_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_subtitle_languages', 'INSERT', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movie_subtitle_languages_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movie_subtitle_languages_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movie_subtitle_languages`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movie_subtitle_languages', 'UPDATE', NULL);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movies_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movies_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`movies`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movies', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movies_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movies_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`movies`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movies', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`movies_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`movies_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`movies`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('movies', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orderlines_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orderlines_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`orderlines`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('orderlines', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orderlines_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orderlines_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`orderlines`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('orderlines', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orderlines_DELETE_ORPHANED_ORDER` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orderlines_DELETE_ORPHANED_ORDER`
AFTER DELETE ON `movie_rental_db`.`orderlines`
FOR EACH ROW
BEGIN
	-- For some reason it gives syntax errors when trying to create a second AFTER DELETE trigger, so ill put it here for now
    CALL CreateLogEntry('orderlines', 'DELETE', OLD.ID);
    
    -- Delete the corrosponding order if there are no more orderline items connected to it
	SET @orderlineItems = (SELECT COUNT(*) FROM orderlines WHERE orderlines.OrderID = OLD.OrderID);
	IF @orderlineItems = 0 THEN 
	   DELETE FROM Orders WHERE ID = OLD.OrderID;
	END IF;
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orders_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orders_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`orders`
FOR EACH ROW
BEGIN
	 CALL CreateLogEntry('orders', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orders_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orders_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`orders`
FOR EACH ROW
BEGIN
	 CALL CreateLogEntry('orders', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`orders_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`orders_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`orders`
FOR EACH ROW
BEGIN
	 CALL CreateLogEntry('orders', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`paypal_payment_methods_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`paypal_payment_methods_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`paypal_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('paypal_payment_methods', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`paypal_payment_methods_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`paypal_payment_methods_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`paypal_payment_methods`
FOR EACH ROW
BEGIN
	 CALL CreateLogEntry('paypal_payment_methods', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`paypal_payment_methods_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`paypal_payment_methods_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`paypal_payment_methods`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('paypal_payment_methods', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`people_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`people_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`people`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('people', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`people_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`people_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`people`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('people', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`people_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`people_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`people`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('people', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`publishers_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`publishers_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('publishers', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`publishers_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`publishers_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('publishers', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`publishers_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`publishers_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`publishers`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('publishers', 'UPDATE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`support_tickets_AFTER_DELETE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`support_tickets_AFTER_DELETE`
AFTER DELETE ON `movie_rental_db`.`support_tickets`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('support_tickets', 'DELETE', OLD.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`support_tickets_AFTER_INSERT` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`support_tickets_AFTER_INSERT`
AFTER INSERT ON `movie_rental_db`.`support_tickets`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('support_tickets', 'INSERT', NEW.ID);
END$$


USE `movie_rental_db`$$
DROP TRIGGER IF EXISTS `movie_rental_db`.`support_tickets_AFTER_UPDATE` $$
USE `movie_rental_db`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `movie_rental_db`.`support_tickets_AFTER_UPDATE`
AFTER UPDATE ON `movie_rental_db`.`support_tickets`
FOR EACH ROW
BEGIN
	CALL CreateLogEntry('support_tickets', 'UPDATE', OLD.ID);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
