-- MySQL Script generated by MySQL Workbench
-- Sun Feb 22 23:20:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movie_rental_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_rental_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_rental_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `movie_rental_db` ;

-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `Balance` DECIMAL(19,2) NULL DEFAULT NULL,
  `PasswordHash` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts_card_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts_card_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts_card_payment_methods` (
  `AccountID` INT UNSIGNED NOT NULL,
  `CardID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AccountID`, `CardID`),
  CONSTRAINT `FK_accounts_card_payment_methods_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_accounts_card_payment_methods_card`
    FOREIGN KEY (`CardID`)
    REFERENCES `movie_rental_db`.`card_payment_methods` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_accounts_card_payment_methods_card_idx` ON `movie_rental_db`.`accounts_card_payment_methods` (`CardID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`accounts_paypal_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`accounts_paypal_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`accounts_paypal_payment_methods` (
  `AccountID` INT UNSIGNED NOT NULL,
  `PaypalID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`AccountID`, `PaypalID`),
  CONSTRAINT `FK_accounts_paypal_payment_methods_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_accounts_paypal_payment_methods_paypal`
    FOREIGN KEY (`PaypalID`)
    REFERENCES `movie_rental_db`.`paypal_payment_methods` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_accounts_paypal_payment_methods_paypal_idx` ON `movie_rental_db`.`accounts_paypal_payment_methods` (`PaypalID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`card_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`card_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`card_payment_methods` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CardNumber` VARCHAR(19) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_bookmarks` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_bookmarks` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `BookmarkTime` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`, `MovieID`),
  CONSTRAINT `FK_customer_bookmarks_customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_customer_bookmarks_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_bookmarks_movies_idx` ON `movie_rental_db`.`customer_bookmarks` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_rentings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_rentings` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_rentings` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `PeriodStart` BIGINT UNSIGNED NULL DEFAULT NULL,
  `PeriodEnd` BIGINT UNSIGNED NULL DEFAULT NULL,
  `Price` DECIMAL(19,2) NULL DEFAULT NULL,
  `ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_customer_rentings_customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_customer_rentings_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_rentings_customers` ON `movie_rental_db`.`customer_rentings` (`CustomerID` ASC) VISIBLE;

CREATE INDEX `FK_customer_rentings_movies_idx` ON `movie_rental_db`.`customer_rentings` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`customer_watchtracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`customer_watchtracking` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`customer_watchtracking` (
  `CustomerID` INT UNSIGNED NOT NULL,
  `MovieID` INT UNSIGNED NOT NULL,
  `TimeStamp` BIGINT NULL DEFAULT NULL,
  `SecondsInMovie` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`, `MovieID`),
  CONSTRAINT `FK_customer_watchtracking_customers`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_customer_watchtracking_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_customer_bookmarks_movies_idx` ON `movie_rental_db`.`customer_watchtracking` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`genres` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`genres` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`giftcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`giftcards` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`giftcards` (
  `ID` INT UNSIGNED NOT NULL,
  `CodeHash` BIGINT NULL DEFAULT NULL,
  `Amount` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`languages` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CountryCode` VARCHAR(10) NULL DEFAULT NULL,
  `Name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_actors` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_actors` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PersonID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PersonID`),
  CONSTRAINT `FK_Movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`),
  CONSTRAINT `FK_People`
    FOREIGN KEY (`PersonID`)
    REFERENCES `movie_rental_db`.`people` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_People_idx` ON `movie_rental_db`.`movie_actors` (`PersonID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_directors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_directors` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_directors` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PersonID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PersonID`),
  CONSTRAINT `FK_Movies0`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`),
  CONSTRAINT `FK_People0`
    FOREIGN KEY (`PersonID`)
    REFERENCES `movie_rental_db`.`people` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_People_idx` ON `movie_rental_db`.`movie_directors` (`PersonID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_genres` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_genres` (
  `MovieID` INT UNSIGNED NOT NULL,
  `GenreID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `GenreID`),
  CONSTRAINT `FK_genres_movies`
    FOREIGN KEY (`GenreID`)
    REFERENCES `movie_rental_db`.`genres` (`ID`),
  CONSTRAINT `FK_movies_genres`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Genres_idx` ON `movie_rental_db`.`movie_genres` (`GenreID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_publishers` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_publishers` (
  `MovieID` INT UNSIGNED NOT NULL,
  `PublisherID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `PublisherID`),
  CONSTRAINT `FK_movies_publishers`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`),
  CONSTRAINT `FK_publishers_movies`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `movie_rental_db`.`publishers` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Genres_idx` ON `movie_rental_db`.`movie_publishers` (`PublisherID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_spoken_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_spoken_languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_spoken_languages` (
  `MovieID` INT UNSIGNED NOT NULL,
  `LanguageID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `LanguageID`),
  CONSTRAINT `FK_Language0`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `movie_rental_db`.`languages` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Movie0`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Language_idx` ON `movie_rental_db`.`movie_spoken_languages` (`LanguageID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movie_subtitle_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movie_subtitle_languages` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movie_subtitle_languages` (
  `MovieID` INT UNSIGNED NOT NULL,
  `LanguageID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MovieID`, `LanguageID`),
  CONSTRAINT `FK_Language`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `movie_rental_db`.`languages` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Movie`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_Language_idx` ON `movie_rental_db`.`movie_subtitle_languages` (`LanguageID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`movies` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`movies` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL DEFAULT NULL,
  `RuntimeSeconds` INT NULL DEFAULT NULL,
  `MinimumAge` TINYINT NULL DEFAULT NULL,
  `Price` DECIMAL(2,0) NULL DEFAULT NULL,
  `ReleaseDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`orderlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`orderlines` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`orderlines` (
  `AccountID` INT UNSIGNED NULL DEFAULT NULL,
  `MovieID` INT UNSIGNED NULL DEFAULT NULL,
  `ID` INT UNSIGNED NOT NULL,
  `GiftcardID` INT UNSIGNED NULL DEFAULT NULL,
  `OrderID` INT UNSIGNED NULL DEFAULT NULL,
  `Price` DECIMAL(19,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_orderlines_accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`),
  CONSTRAINT `FK_orderlines_giftcards`
    FOREIGN KEY (`GiftcardID`)
    REFERENCES `movie_rental_db`.`giftcards` (`ID`),
  CONSTRAINT `FK_orderlines_movies`
    FOREIGN KEY (`MovieID`)
    REFERENCES `movie_rental_db`.`movies` (`ID`),
  CONSTRAINT `FK_orderlines_order`
    FOREIGN KEY (`OrderID`)
    REFERENCES `movie_rental_db`.`orders` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_orderlines_accounts_idx` ON `movie_rental_db`.`orderlines` (`AccountID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_giftcards_idx` ON `movie_rental_db`.`orderlines` (`GiftcardID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_order_idx` ON `movie_rental_db`.`orderlines` (`OrderID` ASC) VISIBLE;

CREATE INDEX `FK_orderlines_movies_idx` ON `movie_rental_db`.`orderlines` (`MovieID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`orders` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`orders` (
  `ID` INT UNSIGNED NOT NULL,
  `OrderTimeStamp` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`paypal_payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`paypal_payment_methods` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`paypal_payment_methods` (
  `Username` VARCHAR(100) NOT NULL,
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(120) NULL DEFAULT NULL,
  `Password` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`people` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`people` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(200) NULL DEFAULT NULL,
  `LastName` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`publishers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`publishers` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`publishers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `movie_rental_db`.`support_tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`support_tickets` ;

CREATE TABLE IF NOT EXISTS `movie_rental_db`.`support_tickets` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NULL DEFAULT NULL,
  `Description` VARCHAR(800) NULL DEFAULT NULL,
  `CreationDate` BIGINT NULL DEFAULT NULL,
  `CreatedBy` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_support_ticks_created_by`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `movie_rental_db`.`accounts` (`ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `FK_support_ticks_created_by_idx` ON `movie_rental_db`.`support_tickets` (`CreatedBy` ASC) VISIBLE;

USE `movie_rental_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `movie_rental_db`.`all_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_rental_db`.`all_accounts` (`ID` INT, `Name` INT, `PhoneNumber` INT, `Balance` INT);

-- -----------------------------------------------------
-- Placeholder table for view `movie_rental_db`.`all_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_rental_db`.`all_movies` (`ID` INT, `Title` INT, `RuntimeSeconds` INT, `MinimumAge` INT, `Price` INT, `ReleaseDate` INT);

-- -----------------------------------------------------
-- View `movie_rental_db`.`all_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`all_accounts`;
DROP VIEW IF EXISTS `movie_rental_db`.`all_accounts` ;
USE `movie_rental_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `movie_rental_db`.`all_accounts` AS select `movie_rental_db`.`accounts`.`ID` AS `ID`,`movie_rental_db`.`accounts`.`Name` AS `Name`,`movie_rental_db`.`accounts`.`PhoneNumber` AS `PhoneNumber`,`movie_rental_db`.`accounts`.`Balance` AS `Balance` from `movie_rental_db`.`accounts`;

-- -----------------------------------------------------
-- View `movie_rental_db`.`all_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie_rental_db`.`all_movies`;
DROP VIEW IF EXISTS `movie_rental_db`.`all_movies` ;
USE `movie_rental_db`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `movie_rental_db`.`all_movies` AS select `movie_rental_db`.`movies`.`ID` AS `ID`,`movie_rental_db`.`movies`.`Title` AS `Title`,`movie_rental_db`.`movies`.`RuntimeSeconds` AS `RuntimeSeconds`,`movie_rental_db`.`movies`.`MinimumAge` AS `MinimumAge`,`movie_rental_db`.`movies`.`Price` AS `Price`,`movie_rental_db`.`movies`.`ReleaseDate` AS `ReleaseDate` from `movie_rental_db`.`movies`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
